# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "蒲公英测试版"
  lane :shipper do |options| # option用于接收我们的外部参数，这里可以传入当前build的描述信息到蒲公英平台
    gym(
        clean:true, # 打包前clean项目
        scheme:"JS_Shipper", # scheme
        export_method:"development", # 导出方式
        configuration:"Debug", # 环境
        output_directory:"/Users/jason_hzb/Desktop/fastlane", # 打包后的ipa文件存放的目录
        output_name:"JS_Shipper" # ipa 文件名
       )
    #蒲公英的配置 替换为自己的api_key和user_key
    pgyer(api_key: "24ab778fdefd56713d8840d4fb7126af", user_key: "bee712f25eab64ded9cc4d14f0f5aa53", password: "js", install_type: "2", update_description: options[:desc])
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :driver do |options| # option用于接收我们的外部参数，这里可以传入当前build的描述信息到蒲公英平台
    gym(
        clean:true, # 打包前clean项目
        scheme:"JS_Driver", # scheme
        export_method:"development", # 导出方式
        configuration:"Debug", # 环境
        output_directory:"/Users/jason_hzb/Desktop/fastlane", # 打包后的ipa文件存放的目录
        output_name:"JS_Driver" # ipa 文件名
       )
    #蒲公英的配置 替换为自己的api_key和user_key
    pgyer(api_key: "24ab778fdefd56713d8840d4fb7126af", user_key: "bee712f25eab64ded9cc4d14f0f5aa53", password: "js", install_type: "2", update_description: options[:desc])
    # add actions here: https://docs.fastlane.tools/actions
  end
end
